wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  save_dir: "${paths.output_dir}"
  offline: False
  id: null
  anonymous: null
  project: "COCO"
  log_model: False
  prefix: ""
  entity: "chlwhdtn8725-shamyook-university"
