name: od-hydra
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - cpython=3.11.11
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - ffmpeg=4.3
  - filelock=3.16.1
  - freetype=2.10.4
  - fsspec=2024.12.0
  - giflib=5.2.2
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.1
  - idna=3.10
  - intel-openmp=2023.1.0
  - jinja2=3.1.5
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.13.5
  - lightning=2.5.0.post0
  - lightning-utilities=0.11.9
  - llvm-openmp=12.0.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.4.2
  - numpy=2.2.1
  - openh264=2.1.1
  - openssl=3.4.0
  - packaging=24.2
  - pillow=9.4.0
  - pip=24.2
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.11.11
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-lightning=2.5.0.post0
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.13.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchmetrics=1.6.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - albucore==0.0.23
      - albumentations==1.4.24
      - alembic==1.14.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - autopage==0.5.2
      - click==8.1.8
      - cliff==4.8.0
      - cmaes==0.11.1
      - cmd2==2.5.8
      - colorlog==6.9.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - fonttools==4.55.3
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.1.1
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - mako==1.3.8
      - markdown-it-py==3.0.0
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - optuna==2.10.1
      - pandas==2.2.3
      - pbr==6.1.0
      - platformdirs==4.3.6
      - prettytable==3.12.0
      - protobuf==5.29.2
      - psutil==6.1.1
      - pycocotools==2.0.8
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pyperclip==1.9.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - rich==13.9.4
      - rootutils==1.0.7
      - scikit-learn==1.6.0
      - scipy==1.15.0
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - simsimd==6.2.1
      - six==1.17.0
      - smmap==5.0.2
      - sqlalchemy==2.0.36
      - stevedore==5.4.0
      - stringzilla==3.11.3
      - threadpoolctl==3.5.0
      - tzdata==2024.2
      - wandb==0.19.2
      - wcwidth==0.2.13
