defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "${model.net.model_name}-{epoch:02d}-{val_mAP:.2f}"
  monitor: "val_mAP"
  mode: "max"
  save_last: True
  save_top_k: 1

early_stopping:
  monitor: "val_mAP"
  patience: 10
  mode: "max"

model_summary:
  max_depth: -1
