model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "{model_name}-{epoch:02d}-{val_mAP:.4f}"  
  monitor: "val_mAP"  
  mode: "max"
  save_last: True
  save_top_k: 1
  auto_insert_metric_name: True
  save_weights_only: False
  every_n_epochs: 1
  verbose: True