name: od
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.6.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.14
  - cairo=1.16.0
  - certifi=2024.12.14
  - charset-normalizer=3.3.2
  - contourpy=1.3.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cython=3.0.11
  - dbus=1.13.18
  - eigen=3.4.0
  - eval-type-backport=0.2.2
  - eval_type_backport=0.2.2
  - expat=2.6.4
  - ffmpeg=4.2.2
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.6.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.7
  - imageio=2.33.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcups=2.4.2
  - libcurand=10.3.7.77
  - libcurl=8.11.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lightning=2.5.0.post0
  - lightning-utilities=0.11.9
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - mysql=8.4.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.42
  - pillow=11.0.0
  - pip=24.2
  - pixman=0.40.0
  - pycocotools=2.0.8
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-lightning=2.5.0.post0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qt-main=5.15.2
  - readline=8.2
  - requests=2.32.3
  - scikit-image=0.24.0
  - scikit-learn=1.6.0
  - scipy=1.14.1
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tifffile=2024.12.12
  - tk=8.6.14
  - tomli=2.0.1
  - torchaudio=2.5.1
  - torchmetrics=1.6.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tqdm=4.66.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - x264=1!157.20191217
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - albucore==0.0.23
      - albumentations==1.4.24
      - click==8.1.8
      - docker-pycreds==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - platformdirs==4.3.6
      - protobuf==5.29.2
      - psutil==6.1.1
      - pygments==2.18.0
      - rich==13.9.4
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - simsimd==6.2.1
      - smmap==5.0.1
      - stringzilla==3.11.3
      - wandb==0.19.1
