defaults:
  - _self_
  - data: coco  
  - model: coco
  - callbacks: default
  - logger: wandb  
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "train"
tags: ["dev"]

train: True
test: True

seed: 36

model:
  net:
    model_name: "mask_rcnn"
  batch_size: 32
  
trainer:
  max_epochs: 3

  precision: "32-true"

data:
  batch_size: ${model.batch_size}

ckpt_path: null