# @package _global_

defaults:
  - _self_
  - data: coco # choose datamodule with `test_dataloader()` for evaluation
  - model: coco
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

task_name: "predict"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

prediction_output_dir: ${hydra:runtime.output_dir}