# @package _global_

defaults:
  - _self_
  - data: pascal # choose datamodule with `test_dataloader()` for evaluation
  - model: pascal
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

task_name: "predict"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
